In [34]:
import pandas as pd
import numpy as np

In [35]:
# GDP and military data
data = pd.read_excel(r'C:\Users\admin\Downloads\Popular Indicators.xlsx')

# education data
edu_data = pd.read_excel(r'C:\Users\admin\Desktop\Individual-Project\Education Expenditure.xls')

# healthcare data
health_data = pd.read_excel(r'Health Expenditure.xls')

In [36]:
data.columns

Index(['Series Name', 'Series Code', 'Country Name', 'Country Code',
       '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]',
       '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]',
       '2019 [YR2019]', '2020 [YR2020]'],
      dtype='object')

In [37]:
#  G20 countries
G20Countries = ['Argentina', 'Australia', 'Brazil', 'Canada', 
'China', 'France', 'Germany', 'India', 'Indonesia', 'Italy', 
'Japan', 'Korea, Rep.', 'Mexico', 'Russian Federation', 'Saudi Arabia', 
'South Africa', 'Turkey', 'United Kingdom', 'United States', 'European Union']

years = ['2011','2012', '2013', '2014', '2015',
           '2016', '2017', '2018', '2019']
# Series Name 
# NY.GDP.MKTP.CD is GDP current USD
# MS.MIL.XPND.GD.ZS IS Military expenditure (% of GDP)
# NY.GDP.PCAP.CD is GDP per capita (current US$)
# population is SP.POP.TOTL
series_list = ['GDP (current US$)', 'Military expenditure (% of GDP)', 'GDP per capita (current US$)', 'Population, total']

In [38]:
def get_gdp_data(data):
# filter for countries
    sub_data = data[data['Country Name'].isin(G20Countries)]
    sub_data.columns = ['Series Name', 'Series Code', 'Country Name', 'Country Code', '2011',
           '2012', '2013', '2014', '2015',
           '2016', '2017', '2018', '2019', '2020']
    processed_df = pd.DataFrame()
    for idx in range(len(series_list)):
        temp = sub_data[sub_data['Series Name'] == series_list[idx]]
        pivoted = pd.melt(temp, id_vars='Country Name', value_vars=years, value_name=series_list[idx])
        if idx > 0:
            temp_2 = pd.merge(temp_2, pivoted, on =['Country Name', 'variable'])
        else:
            temp_2 = pivoted
    temp_2 = temp_2.replace('..', np.NaN)
    temp_2 = temp_2.groupby('Country Name').apply(lambda group: group.interpolate(method='linear'))
    return temp_2

gdp_data = get_gdp_data(data)
gdp_data.columns = ['Country Name', 'Year', 'GDP (current US$)',
       'Military expenditure (% of GDP)', 'GDP per capita (current US$)',
       'Population, total']

In [39]:
def transform_edu_data(df):
    sub_df = df[df['Country Name'].isin(G20Countries)]
#     print(sub_df)
    pivoted = pd.melt(sub_df, id_vars='Country Name', value_vars=years)
#     temp_2 = pivoted.replace('..', np.NaN)
    pivoted = pivoted.groupby('Country Name').apply(lambda group: group.interpolate(method='index'))
    pivoted = pivoted.groupby("Country Name").apply(lambda x: x.fillna(method='bfill'))
    return pivoted

edu_data_processed = transform_edu_data(edu_data)
edu_data_processed.columns = ['Country Name', 'Year', 'Education expenditure (% of GDP)']
edu_data_processed

           Country Name  Year  Education expenditure (% of GDP)
0             Argentina  2011                           5.29063
1             Australia  2011                           5.07451
2                Brazil  2011                           5.73741
3                Canada  2011                           5.27444
4                 China  2011                               NaN
..                  ...   ...                               ...
175  Russian Federation  2019                           3.74303
176        Saudi Arabia  2019                               NaN
177              Turkey  2019                               NaN
178       United States  2019                           4.96174
179        South Africa  2019                           6.15899

[180 rows x 3 columns]

In [40]:
# edu_data_processed[edu_data_processed['Government expenditure on education, total (% of GDP)'].isna()
#                   ].sort_values(['Country Name','Year'])

In [41]:
healthcare_list = ['Current health expenditure per capita, PPP (current international $)', 'Current health expenditure (% of GDP)']
def healthcare_data(df):
    sub_data = df[df['Country Name'].isin(G20Countries)]
    for idx in range(len(healthcare_list)):
        temp = sub_data[sub_data['Indicator Name'] == healthcare_list[idx]]
        pivoted = pd.melt(temp, id_vars='Country Name', value_vars=years, value_name=healthcare_list[idx])
        if idx > 0:
            temp_2 = pd.merge(temp_2, pivoted, on =['Country Name', 'variable'])
        else:
            temp_2 = pivoted
    temp_2 = temp_2.groupby('Country Name').apply(lambda group: group.interpolate(method='index'))
    temp_2 = temp_2.groupby("Country Name").apply(lambda x: x.fillna(method='bfill'))
    return temp_2

health_data_processed = healthcare_data(health_data)
health_data_processed.columns = ['Country Name', 'Year', 
                                 'Current health expenditure per capita, PPP (current international $)',
                                'Health expenditure (% of GDP)']

In [42]:
final_data = pd.merge(gdp_data, health_data_processed, on=['Country Name', 'Year'])
final_data = pd.merge(final_data, edu_data_processed, on=['Country Name', 'Year'])
final_data.head()

,Country Name,Year,GDP (current US$),Military expenditure (% of GDP),GDP per capita (current US$),"Population, total","Current health expenditure per capita, PPP (current international $)",Health expenditure (% of GDP),Education expenditure (% of GDP)
0,European Union,2011,1.574184e+13,1.501848,35716.273663,440746976,3297.408614,NaN,5.01738
1,Argentina,2011,5.301633e+11,0.764287,12848.864197,41261490,1648.187744,8.396563,5.29063
2,Australia,2011,1.396650e+12,1.769390,62517.833747,22340024,3770.488281,8.541520,5.07451
3,Brazil,2011,2.616201e+12,1.411851,13245.612500,197514534,1166.133545,7.788301,5.73741
4,Canada,2011,1.788648e+12,1.196084,52087.446384,34339328,4278.646973,10.352504,5.27444

In [43]:
# (final_data['Current health expenditure (% of GDP)'] * final_data['GDP (current US$)'])/final_data['Population, total']
final_data['Military expenditure (current US$)'] = (final_data['Military expenditure (% of GDP)']/100) * final_data['GDP (current US$)']
final_data['Education expenditure (current US$)'] = (final_data['Education expenditure (% of GDP)']/100) * final_data['GDP (current US$)']
final_data['Health expenditure (current US$)'] = (final_data['Health expenditure (% of GDP)']/100) * final_data['GDP (current US$)']

# per capita
final_data['Military expenditure per capita'] = final_data['Military expenditure (current US$)'] / final_data['Population, total']
final_data['Education expenditure per capita'] = final_data['Education expenditure (current US$)'] / final_data['Population, total']
final_data['Health expenditure per capita'] = final_data['Health expenditure (current US$)'] / final_data['Population, total']

In [44]:
final_data['Year'] = final_data['Year'].astype('int')
final_data = final_data[final_data['Year']>=2014]

In [45]:
len(final_data['Country Name'].unique())

20

In [46]:
# create military expenditure sheet
def transformation(final_data, label):
    
    years = final_data['Year'].unique()
    
    military_exp = final_data[['Country Name', 'Year', 
                            label + ' expenditure (% of GDP)', 
                            label + ' expenditure (current US$)', 
                            label + ' expenditure per capita']]

    military_exp.head()

    col_list = [label + ' expenditure (% of GDP)', 
                label + ' expenditure (current US$)', 
                label + ' expenditure per capita']

    transformed_military = pd.DataFrame()
    for idx in col_list:
        temp = pd.pivot_table(military_exp,index=["Country Name"],values=[idx],
                       columns=["Year"])
        temp = pd.pivot_table(military_exp,index=["Country Name"],values=[idx],
                       columns=["Year"])
        temp.columns = temp.columns.droplevel()

        temp['Metric'] = idx
        
#         temp[['2014', '2015', '2016', '2017', '2018', '2019']] = round(temp[['2014', 
#                                                                              '2015', '2016', 
#                                                                              '2017', '2018', '2019']], 2)

#         if idx == label+' expenditure (% of GDP)':
#             for year in years:
#                 temp[year] = temp[year].apply(lambda x: "{0:,.2f}%".format((x)))
#         else:
#             for year in years:
#                 temp[year] = temp[year].apply(lambda x: "${0:,.2f}".format((x)))

        transformed_military = transformed_military.append(temp)
    
    return transformed_military
#     break
transformed_military = transformation(final_data, 'Military')
transformed_education = transformation(final_data, 'Education')
transformed_health = transformation(final_data, 'Health')

# military_exp

In [47]:
transformed_health.columns

Index([2014, 2015, 2016, 2017, 2018, 2019, 'Metric'], dtype='object', name='Year')

In [59]:
def get_per_change(df):
    per_change_df = pd.DataFrame()

    per_change_df['Metric'] = df['Metric']
    per_change_df['2015_per_change'] = round(((df.iloc[:,1] - df.iloc[:,0])/df.iloc[:,0])*100, 2)

    per_change_df['2016_per_change'] = round(((df.iloc[:,2] - df.iloc[:,1])/df.iloc[:,1])*100, 2)

    per_change_df['2017_per_change'] = round(((df.iloc[:,3] - df.iloc[:,2])/df.iloc[:,2])*100, 2)

    per_change_df['2018_per_change'] = round(((df.iloc[:,4] -  df.iloc[:,3])/df.iloc[:,3])*100, 2)

    per_change_df['2019_per_change'] = round(((df.iloc[:,5] -  df.iloc[:,4])/df.iloc[:,5])*100, 2)
    
    return per_change_df


perchange_health = get_per_change(transformed_health)
perchange_education = get_per_change(transformed_education)
perchange_military= get_per_change(transformed_military)

In [60]:
perchange_military

,Metric,2015_per_change,2016_per_change,2017_per_change,2018_per_change,2019_per_change
Country Name,,,,,,
Argentina,Military expenditure (% of GDP),-3.19,-4.35,5.29,-0.18,0.00
Australia,Military expenditure (% of GDP),9.95,6.86,-4.06,-5.80,0.00
Brazil,Military expenditure (% of GDP),2.65,-1.13,5.14,3.90,0.00
Canada,Military expenditure (% of GDP),15.91,0.72,11.65,-3.15,0.00
China,Military expenditure (% of GDP),0.06,0.94,-1.48,-1.61,0.00
European Union,Military expenditure (% of GDP),-0.50,0.93,1.81,0.52,0.00
France,Military expenditure (% of GDP),1.77,2.53,0.96,-2.37,0.00
Germany,Military expenditure (% of GDP),-0.43,1.06,3.72,-0.03,0.00
India,Military expenditure (% of GDP),-3.67,4.21,0.13,-3.61,0.00
Indonesia,Military expenditure (% of GDP),14.03,-10.85,1.73,-10.93,0.00
Italy,Military expenditure (% of GDP),-5.96,10.65,2.01,-2.48,0.00
Japan,Military expenditure (% of GDP),-0.93,-1.93,-0.94,-0.74,0.00
"Korea, Rep.",Military expenditure (% of GDP),-0.60,-1.39,-1.50,1.89,0.00
Mexico,Military expenditure (% of GDP),0.39,-15.49,-10.17,7.27,0.00
Russian Federation,Military expenditure (% of GDP),18.48,12.13,-22.36,-7.18,0.00
Saudi Arabia,Military expenditure (% of GDP),24.80,-25.91,3.83,-14.40,0.00
South Africa,Military expenditure (% of GDP),-0.92,-2.15,-2.96,-5.94,0.00
Turkey,Military expenditure (% of GDP),-2.91,11.94,0.03,21.09,0.00
United Kingdom,Military expenditure (% of GDP),-4.58,-2.63,-2.19,0.63,0.00
United States,Military expenditure (% of GDP),-6.01,-1.95,-3.08,1.73,0.00
Argentina,Military expenditure (current US$),9.40,-10.34,21.37,-19.26,-15.61
Australia,Military expenditure (current US$),1.27,-4.43,5.57,1.55,-2.96
Brazil,Military expenditure (current US$),-24.67,-1.48,20.78,-5.03,-2.49
Canada,Military expenditure (current US$),0.01,-1.08,20.53,0.74,1.16
China,Military expenditure (current US$),5.66,2.50,7.97,11.05,3.12
European Union,Military expenditure (current US$),-13.78,3.43,8.07,8.68,-2.18
France,Military expenditure (current US$),-13.00,3.92,6.02,4.88,-2.66
Germany,Military expenditure (current US$),-13.84,4.25,9.67,7.71,-2.70
India,Military expenditure (current US$),-0.63,13.69,15.74,-1.41,5.63
Indonesia,Military expenditure (current US$),10.19,-3.50,10.87,-8.59,6.88
Italy,Military expenditure (current US$),-20.04,13.06,6.69,3.69,-4.22
Japan,Military expenditure (current US$),-10.34,9.98,-2.06,1.05,2.50
"Korea, Rep.",Military expenditure (current US$),-1.84,0.92,6.63,7.95,-4.76
Mexico,Military expenditure (current US$),-10.60,-22.18,-3.51,13.10,2.99
Russian Federation,Military expenditure (current US$),-21.55,5.00,-4.27,-1.55,1.78
Saudi Arabia,Military expenditure (current US$),7.95,-26.97,10.86,-2.23,0.81
South Africa,Military expenditure (current US$),-10.32,-8.70,14.46,-0.89,-4.80
Turkey,Military expenditure (current US$),-10.64,12.45,-1.25,9.54,-2.25
United Kingdom,Military expenditure (current US$),-8.79,-10.42,-3.21,7.97,-1.19
United States,Military expenditure (current US$),-2.26,0.67,0.95,7.18,3.96
Argentina,Military expenditure per capita,8.23,-11.28,20.12,-20.08,-16.77
Australia,Military expenditure per capita,-0.18,-5.91,3.81,0.00,-4.53
Brazil,Military expenditure per capita,-25.30,-2.29,19.81,-5.77,-3.26
Canada,Military expenditure per capita,-0.74,-2.19,19.10,-0.65,-0.26
China,Military expenditure per capita,5.13,1.95,7.37,10.55,2.78
European Union,Military expenditure per capita,-13.96,3.21,7.91,8.52,-2.34
France,Military expenditure per capita,-13.31,3.65,5.80,4.72,-2.81
Germany,Military expenditure per capita,-14.59,3.41,9.26,7.38,-2.98
India,Military expenditure per capita,-1.73,12.45,14.52,-2.43,4.67
Indonesia,Military expenditure per capita,8.80,-4.67,9.57,-9.62,5.84
Italy,Military expenditure per capita,-19.96,13.25,6.85,3.88,-4.01
Japan,Military expenditure per capita,-10.25,10.11,-1.90,1.25,2.70
"Korea, Rep.",Military expenditure per capita,-2.36,0.52,6.33,7.44,-4.97
Mexico,Military expenditure per capita,-11.71,-23.11,-4.63,11.83,1.92
Russian Federation,Military expenditure per capita,-21.70,4.82,-4.37,-1.54,1.85
Saudi Arabia,Military expenditure per capita,5.23,-28.60,8.66,-3.97,-0.86
South Africa,Military expenditure per capita,-11.68,-10.03,12.86,-2.23,-6.21
Turkey,Military expenditure per capita,-12.12,10.63,-2.81,7.92,-3.62
United Kingdom,Military expenditure per capita,-9.51,-11.09,-3.87,7.31,-1.76
United States,Military expenditure per capita,-2.98,-0.05,0.31,6.62,3.50

In [50]:
len(transformed_education.index)

48

In [51]:
from collections import Counter 

list((Counter(transformed_military.index.values)-Counter(transformed_health.index.values)).elements()) 


# transformed_education.index.values

['European Union', 'European Union', 'European Union']

In [52]:
# comparison sheet
df = final_data[['Country Name', 'Year', 'Military expenditure (% of GDP)', 
                 'Health expenditure (% of GDP)', 'Education expenditure (% of GDP)', 
                 'GDP (current US$)','Population, total']]

df['Metric'] = ' Percentage of GDP'

df.columns = ['Country Name', 'Year', 'Military Expenditure', 
                 'Health Expenditure', 'Education Expenditure', 
                 'GDP (current US$)','Population', 'Metric']

df_2 = final_data[['Country Name', 'Year', 'Military expenditure (current US$)', 
                 'Health expenditure (current US$)', 'Education expenditure (current US$)', 
                 'GDP (current US$)','Population, total']]

df_2['Metric'] = 'US Dollar($)'

df_2.columns = ['Country Name', 'Year', 'Military Expenditure', 
                 'Health Expenditure', 'Education Expenditure', 
                 'GDP (current US$)','Population', 'Metric']

df_3 = final_data[['Country Name', 'Year', 'Military expenditure per capita', 
                 'Health expenditure per capita', 'Education expenditure per capita', 
                 'GDP (current US$)','Population, total']]

df_3['Metric'] = 'Per Capita'

df_3.columns = ['Country Name', 'Year', 'Military Expenditure', 
                 'Health Expenditure', 'Education Expenditure', 
                 'GDP (current US$)','Population', 'Metric']

compare_df = df.append(df_2)
compare_df = compare_df.append(df_3)

C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [53]:
compare_df['Year'] = compare_df['Year'].astype('int')
compare_df.dtypes

Country Name              object
Year                       int32
Military Expenditure     float64
Health Expenditure       float64
Education Expenditure    float64
GDP (current US$)        float64
Population                 int64
Metric                    object
dtype: object

In [54]:
compare_df = compare_df[compare_df['Year']>=2014]
compare_df

,Country Name,Year,Military Expenditure,Health Expenditure,Education Expenditure,GDP (current US$),Population,Metric
60,European Union,2014,1.408964,NaN,5.123250,1.563306e+13,443576663,Percentage of GDP
61,Argentina,2014,0.878101,8.258233,5.361440,5.263197e+11,42669500,Percentage of GDP
62,Australia,2014,1.781295,9.038034,5.164770,1.467484e+12,23475686,Percentage of GDP
63,Brazil,2014,1.330244,8.396054,5.948480,2.455994e+12,202763735,Percentage of GDP
64,Canada,2014,0.992271,10.055616,5.274440,1.803533e+12,35437435,Percentage of GDP
...,...,...,...,...,...,...,...,...
175,Saudi Arabia,2019,2030.452339,1210.270057,NaN,7.929668e+11,34268528,Per Capita
176,South Africa,2019,58.916335,486.900745,369.625676,3.514316e+11,58558270,Per Capita
177,Turkey,2019,226.456271,381.258897,NaN,7.544117e+11,83429615,Per Capita
178,United Kingdom,2019,753.877637,4074.232337,2321.002967,2.827113e+12,66834405,Per Capita
179,United States,2019,2059.605686,11110.018468,3231.003633,2.137442e+13,328239523,Per Capita

In [55]:
final_data.columns

Index(['Country Name', 'Year', 'GDP (current US$)',
       'Military expenditure (% of GDP)', 'GDP per capita (current US$)',
       'Population, total',
       'Current health expenditure per capita, PPP (current international $)',
       'Health expenditure (% of GDP)', 'Education expenditure (% of GDP)',
       'Military expenditure (current US$)',
       'Education expenditure (current US$)',
       'Health expenditure (current US$)', 'Military expenditure per capita',
       'Education expenditure per capita', 'Health expenditure per capita'],
      dtype='object')

In [56]:
# last data
latest_data = final_data[['Country Name', 'Year', 'GDP (current US$)']]
latest_data = latest_data[latest_data['Year']==2019]
latest_data.shape

(20, 3)

In [61]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('final_data_updated_v3.xlsx', engine='xlsxwriter')

# Write each dataframe to a different worksheet.
final_data.to_excel(writer, sheet_name='full-data')
compare_df.to_excel(writer, sheet_name='Comparison')
latest_data.to_excel(writer, sheet_name='data2019')


transformed_military.to_excel(writer, sheet_name='Military-Expenditure')
transformed_education.to_excel(writer, sheet_name='Education-Expenditure')
transformed_health.to_excel(writer, sheet_name='Health-Expenditure')


perchange_military.to_excel(writer, sheet_name='Military-Expenditure-PerChange')
perchange_education.to_excel(writer, sheet_name='Education-Expenditure-PerChange')
perchange_health.to_excel(writer, sheet_name='Health-Expenditure-PerChange')

# Close the Pandas Excel writer and output the Excel file.
writer.save()